import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Radix UI
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import Providers from "./providers";
import SessionWrapper from "./session";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EzTech | Ez Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <Providers>
            <Theme>{children}</Theme>
          </Providers>
        </SessionWrapper>
        <Toaster />
      </body>
    </html>
  );
}
